clone_depth: 10
skip_tags: true

init:
  - git config --global core.autocrlf input

branches:
  only:
    - deploy

environment:
  SIGNTOOL_PATH: 'C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Bin/SignTool.exe'
  SIGN_WIN_CERTIFICATE_FILE: 'C:/code-sign.pfx'
  SIGN_WIN_CERTIFICATE_PASSWORD:
    secure: nyd9bdkflnyrzMgS67TsFQ==
  AWS_ACCESS_KEY_ID:
    secure: KCNgXhFTqB4ghk+NC/r+lPseHn7DhRnOZDM8E/iqNh4=
  AWS_SECRET_ACCESS_KEY:
    secure: F/5rsDPPy3nj8fe4Dny6G3AwS9dkfW7yImwYJ2z4dyctReBtUsNuS5fu+7wcQ/fC
  GITHUB_TOKEN:
    secure: f9CXKg1qkz7okdybl/u8+dj1tRhBV0kQnhHuBMti/8YDhqr5sca4pK6v86P9fMwY

cache:
  - "node_modules -> package.json"
  - "src\\node_modules -> src\\package.json"
  - "cache -> src\\package.json"
  - "%APPDATA%\\npm-cache"

install:
  - npm install -g npm@3
  - set PATH=%APPDATA%\npm;%PATH%
  - aws s3 cp --region eu-west-1 s3://chatra-io/certs/code-sign.pfx C:/code-sign.pfx
  - npm install -g gulp
  - npm install

before_build:
  - npm test
  - gulp rebuild:32 --verbose

build_script:
# - gulp pack:win32:portable --prod --verbose
  - gulp pack:win32:installer --prod --verbose

deploy_script:
  - gulp clean:prev-releases:win32 --verbose
  - gulp publish:github --verbose

artifacts:
  - path: dist\*
